/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

/**
 *
 * @author aname
 */
public class F01_Homepage extends javax.swing.JFrame {

    /**
     * Creates new form F1_Homepage
     */
    public F01_Homepage() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homepage_admin = new javax.swing.JButton();
        homepage_student = new javax.swing.JButton();
        homepage_exit = new javax.swing.JButton();
        homepage_prof = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        homepage_admin.setBorderPainted(false);
        homepage_admin.setContentAreaFilled(false);
        homepage_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_adminActionPerformed(evt);
            }
        });
        jPanel1.add(homepage_admin);
        homepage_admin.setBounds(310, 460, 290, 30);

        homepage_student.setBorderPainted(false);
        homepage_student.setContentAreaFilled(false);
        homepage_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_studentActionPerformed(evt);
            }
        });
        jPanel1.add(homepage_student);
        homepage_student.setBounds(310, 360, 290, 30);

        homepage_exit.setToolTipText("");
        homepage_exit.setBorderPainted(false);
        homepage_exit.setContentAreaFilled(false);
        homepage_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_exitActionPerformed(evt);
            }
        });
        jPanel1.add(homepage_exit);
        homepage_exit.setBounds(800, 500, 60, 30);

        homepage_prof.setBorderPainted(false);
        homepage_prof.setContentAreaFilled(false);
        homepage_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_profActionPerformed(evt);
            }
        });
        jPanel1.add(homepage_prof);
        homepage_prof.setBounds(310, 410, 290, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepage_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_exitActionPerformed
       Finals_enrollment.previousFrame= ("Homepage");
       new F11_Exit().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_homepage_exitActionPerformed

    private void homepage_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_adminActionPerformed
        new F02_AdminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepage_adminActionPerformed

    private void homepage_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_studentActionPerformed
       Finals_enrollment.previousFrame= ("StudentLogin");
       new F09_LoginSS().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_homepage_studentActionPerformed

    private void homepage_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_profActionPerformed
        Finals_enrollment.previousFrame= ("ProfessorLogin");
        new F09_LoginSS().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepage_profActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F01_Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F01_Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F01_Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F01_Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F01_Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homepage_admin;
    private javax.swing.JButton homepage_exit;
    private javax.swing.JButton homepage_prof;
    private javax.swing.JButton homepage_student;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
