/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author aname
 */
public class F02_AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form F2_AdminLogin
     */
    

    public F02_AdminLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admin_clearlogin = new javax.swing.JButton();
        admin_backogin = new javax.swing.JButton();
        admin_registerlogin = new javax.swing.JButton();
        admin_enterlogin = new javax.swing.JButton();
        admin_unhide = new javax.swing.JButton();
        admin_username = new javax.swing.JTextField();
        admin_password = new javax.swing.JPasswordField();
        admin_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        admin_clearlogin.setBorderPainted(false);
        admin_clearlogin.setContentAreaFilled(false);
        admin_clearlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_clearloginActionPerformed(evt);
            }
        });
        jPanel1.add(admin_clearlogin);
        admin_clearlogin.setBounds(420, 380, 70, 40);

        admin_backogin.setBorderPainted(false);
        admin_backogin.setContentAreaFilled(false);
        admin_backogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_backoginActionPerformed(evt);
            }
        });
        jPanel1.add(admin_backogin);
        admin_backogin.setBounds(500, 380, 70, 40);

        admin_registerlogin.setBorderPainted(false);
        admin_registerlogin.setContentAreaFilled(false);
        admin_registerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_registerloginActionPerformed(evt);
            }
        });
        jPanel1.add(admin_registerlogin);
        admin_registerlogin.setBounds(420, 440, 60, 30);

        admin_enterlogin.setBorderPainted(false);
        admin_enterlogin.setContentAreaFilled(false);
        admin_enterlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_enterloginActionPerformed(evt);
            }
        });
        jPanel1.add(admin_enterlogin);
        admin_enterlogin.setBounds(330, 383, 70, 40);

        admin_unhide.setText("jButton1");
        admin_unhide.setBorderPainted(false);
        admin_unhide.setContentAreaFilled(false);
        admin_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(admin_unhide);
        admin_unhide.setBounds(540, 330, 30, 23);

        admin_username.setBackground(new java.awt.Color(255, 255, 255));
        admin_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        admin_username.setBorder(null);
        jPanel1.add(admin_username);
        admin_username.setBounds(370, 250, 160, 30);

        admin_password.setBackground(new java.awt.Color(255, 255, 255));
        admin_password.setForeground(new java.awt.Color(0, 0, 0));
        admin_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        admin_password.setBorder(null);
        jPanel1.add(admin_password);
        admin_password.setBounds(370, 320, 160, 30);

        admin_exit.setBorderPainted(false);
        admin_exit.setContentAreaFilled(false);
        admin_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_exitActionPerformed(evt);
            }
        });
        jPanel1.add(admin_exit);
        admin_exit.setBounds(800, 493, 60, 40);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminlogin.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_backoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_backoginActionPerformed
        Finals_enrollment.previousFrame = ("AdminLogin");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_backoginActionPerformed

    private void admin_enterloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_enterloginActionPerformed
       String uname1 = admin_username.getText();
String pass1 = admin_password.getText();

int a = Finals_enrollment.username.size();
int i;

if (uname1.isEmpty() || pass1.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please enter username and password.");
    return; 
}

if (Finals_enrollment.adminAttempts == 0) {
    JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
    admin_enterlogin.setEnabled(false); 
    admin_username.setEnabled(false); 
    admin_password.setEnabled(false); 

    Finals_enrollment.adminTimer = new Timer(10000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Finals_enrollment.adminAttempts = 3;
            admin_enterlogin.setEnabled(true); 
            admin_username.setEnabled(true); 
            admin_password.setEnabled(true); 
            admin_username.setText("");
            admin_password.setText("");
            JOptionPane.showMessageDialog(null, "You can try logging in again.");
            Finals_enrollment.adminTimer.stop();
        }
    });

            Finals_enrollment.adminTimer.setRepeats(false);
            Finals_enrollment.adminTimer.start();
            return;
        }

        if (Finals_enrollment.username.contains(uname1)) {
            for (i = 0; i < a; i++) {
                if (uname1.equals(Finals_enrollment.username.get(i))) {
                    if (pass1.length() <= 2) {
                        JOptionPane.showMessageDialog(null, "Password too short.");
                        admin_password.setText("");
                        Finals_enrollment.adminAttempts--;
                    } else if (pass1.length() > 500) {
                        JOptionPane.showMessageDialog(null, "Password too long.");
                        admin_password.setText("");
                        Finals_enrollment.adminAttempts--;
                    } else if (!pass1.equals(Finals_enrollment.password.get(i))) {
                        Finals_enrollment.adminAttempts--;
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname1 + ". Attempts left: " + Finals_enrollment.adminAttempts);
                        admin_password.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F14_AdminPortal().setVisible(true);
                        this.setVisible(false);
                    }
                    return;
                }
            }
        } else if (uname1.equals("admin") && pass1.equals("12345")) {
            JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
            new F14_AdminPortal().setVisible(true);
            this.setVisible(false);
        } else {
            Finals_enrollment.adminAttempts--;
            JOptionPane.showMessageDialog(null, "Username doesn't exist or incorrect. Attempts left: " + Finals_enrollment.adminAttempts);
            admin_username.setText("");
            admin_password.setText("");
        }

        if (Finals_enrollment.adminAttempts <= 0) {
            JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
            admin_enterlogin.setEnabled(false); 
            admin_username.setEnabled(false); 
            admin_password.setEnabled(false); 

            Finals_enrollment.adminTimer = new Timer(10000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Finals_enrollment.adminAttempts = 3;
                    admin_enterlogin.setEnabled(true); 
                    admin_username.setEnabled(true); 
                    admin_password.setEnabled(true); 
                    admin_username.setText("");
                    admin_password.setText("");
                    JOptionPane.showMessageDialog(null, "You can try logging in again.");
                    Finals_enrollment.adminTimer.stop();
                }
            });

            Finals_enrollment.adminTimer.setRepeats(false);
            Finals_enrollment.adminTimer.start();
        }

    }//GEN-LAST:event_admin_enterloginActionPerformed

    private void admin_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_unhideActionPerformed
          if (admin_password.getEchoChar() == '*') {  
            admin_password.setEchoChar((char) 0);  
        } 
        else {
            admin_password.setEchoChar('*');  
    }
    }//GEN-LAST:event_admin_unhideActionPerformed

    private void admin_clearloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_clearloginActionPerformed
        admin_password.setText("");
        admin_username.setText("");
    }//GEN-LAST:event_admin_clearloginActionPerformed

    private void admin_registerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_registerloginActionPerformed
        new F03_AdminRegister().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_registerloginActionPerformed

    private void admin_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_exitActionPerformed
        Finals_enrollment.previousFrame = ("AdminExit");
        new F04_AdminPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F02_AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F02_AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F02_AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F02_AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F02_AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_backogin;
    private javax.swing.JButton admin_clearlogin;
    private javax.swing.JButton admin_enterlogin;
    private javax.swing.JButton admin_exit;
    private javax.swing.JPasswordField admin_password;
    private javax.swing.JButton admin_registerlogin;
    private javax.swing.JButton admin_unhide;
    private javax.swing.JTextField admin_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
