package com.mycompany.finals_enrollment;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aname
 */
public class F03_AdminRegister extends javax.swing.JFrame {

    /**
     * Creates new form F3_AdminRegister
     */
    public F03_AdminRegister() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterAccount = new javax.swing.JPanel();
        register_reg = new javax.swing.JButton();
        register_student = new javax.swing.JButton();
        register_prof = new javax.swing.JButton();
        ar_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        RegisterAccount.setLayout(null);

        register_reg.setBorder(null);
        register_reg.setBorderPainted(false);
        register_reg.setContentAreaFilled(false);
        register_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_regActionPerformed(evt);
            }
        });
        RegisterAccount.add(register_reg);
        register_reg.setBounds(620, 250, 140, 120);

        register_student.setBorder(null);
        register_student.setBorderPainted(false);
        register_student.setContentAreaFilled(false);
        register_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_studentActionPerformed(evt);
            }
        });
        RegisterAccount.add(register_student);
        register_student.setBounds(180, 200, 190, 210);

        register_prof.setBorder(null);
        register_prof.setBorderPainted(false);
        register_prof.setContentAreaFilled(false);
        register_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_profActionPerformed(evt);
            }
        });
        RegisterAccount.add(register_prof);
        register_prof.setBounds(430, 250, 140, 120);

        ar_back.setBorderPainted(false);
        ar_back.setContentAreaFilled(false);
        ar_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar_backActionPerformed(evt);
            }
        });
        RegisterAccount.add(ar_back);
        ar_back.setBounds(795, 493, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminreg.png"))); // NOI18N
        RegisterAccount.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(RegisterAccount);
        RegisterAccount.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_regActionPerformed
        Finals_enrollment.previousFrame =("RegistrarRegister");
        new F04_AdminPassword().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_register_regActionPerformed

    private void register_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_studentActionPerformed
        Finals_enrollment.previousFrame =("StudentRegister");
        new F04_AdminPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_register_studentActionPerformed

    private void register_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_profActionPerformed
        Finals_enrollment.previousFrame =("ProfessorRegister");
        new F04_AdminPassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_register_profActionPerformed

    private void ar_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar_backActionPerformed
        Finals_enrollment.previousFrame =("AdminBack");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ar_backActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F03_AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F03_AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F03_AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F03_AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F03_AdminRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegisterAccount;
    private javax.swing.JButton ar_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton register_prof;
    private javax.swing.JButton register_reg;
    private javax.swing.JButton register_student;
    // End of variables declaration//GEN-END:variables
}
