/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import javax.swing.JOptionPane;

/**
 *
 * @author aname
 */
public class F04_AdminPassword extends javax.swing.JFrame {

    /**
     * Creates new form AdminPassword
     */
    public F04_AdminPassword() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminpass = new javax.swing.JPasswordField();
        ap_unhide = new javax.swing.JButton();
        ap_clear = new javax.swing.JButton();
        ap_back = new javax.swing.JButton();
        ap_enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        adminpass.setBackground(new java.awt.Color(255, 255, 255));
        adminpass.setForeground(new java.awt.Color(0, 0, 0));
        adminpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adminpass.setBorder(null);
        jPanel1.add(adminpass);
        adminpass.setBounds(380, 270, 140, 20);

        ap_unhide.setText("jButton1");
        ap_unhide.setBorderPainted(false);
        ap_unhide.setContentAreaFilled(false);
        ap_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(ap_unhide);
        ap_unhide.setBounds(540, 270, 20, 23);

        ap_clear.setBorderPainted(false);
        ap_clear.setContentAreaFilled(false);
        ap_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_clearActionPerformed(evt);
            }
        });
        jPanel1.add(ap_clear);
        ap_clear.setBounds(420, 320, 60, 30);

        ap_back.setBorderPainted(false);
        ap_back.setContentAreaFilled(false);
        ap_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_backActionPerformed(evt);
            }
        });
        jPanel1.add(ap_back);
        ap_back.setBounds(500, 320, 60, 30);

        ap_enter.setBorderPainted(false);
        ap_enter.setContentAreaFilled(false);
        ap_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap_enterMouseClicked(evt);
            }
        });
        ap_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_enterActionPerformed(evt);
            }
        });
        jPanel1.add(ap_enter);
        ap_enter.setBounds(350, 320, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminpass.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ap_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_enterActionPerformed
        
        
        String adminpassw = "yurina";
        if (Finals_enrollment.previousFrame.equals("AdminExit")) {
                if(adminpass.getText().equals(adminpassw)){
            
                System.exit(0);
            
        }
            else{
                JOptionPane.showMessageDialog(null, "Wrong password");
                adminpass.setText("");
                
         }
        } else if (!Finals_enrollment.previousFrame.equals("AdminExit")) {
                if(adminpass.getText().equals(adminpassw)){
            
                JOptionPane.showMessageDialog(null, "Successful");
                new F05_Disclaimer().setVisible(true);
                this.setVisible(false);
            
            
        }
            else{
                JOptionPane.showMessageDialog(null, "Wrong password");
                adminpass.setText("");
                }    
         }
    }//GEN-LAST:event_ap_enterActionPerformed

    private void ap_enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap_enterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_enterMouseClicked

    private void ap_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_clearActionPerformed
        adminpass.setText("");
    }//GEN-LAST:event_ap_clearActionPerformed

    private void ap_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_backActionPerformed
       Finals_enrollment.previousFrame = ("AdminPassword");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ap_backActionPerformed

    private void ap_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_unhideActionPerformed
        if (adminpass.getEchoChar() == '*') {  
             adminpass.setEchoChar((char) 0);  
    } 
        else {
            adminpass.setEchoChar('*'); 
    }
    }//GEN-LAST:event_ap_unhideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F04_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F04_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F04_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F04_AdminPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F04_AdminPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminpass;
    private javax.swing.JButton ap_back;
    private javax.swing.JButton ap_clear;
    private javax.swing.JButton ap_enter;
    private javax.swing.JButton ap_unhide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
