package com.mycompany.finals_enrollment;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aname
 */
public class F06_StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form F5_StudentRegister
     */
    public F06_StudentRegister() {
        initComponents();
        setLocationRelativeTo(null);
        sr_name.setBackground(new Color(0, 0, 0, 0));
        sr_username.setBackground(new Color(0, 0, 0, 0));
        sr_password.setBackground(new Color(0, 0, 0, 0));
        sr_conpass.setBackground(new Color(0, 0, 0, 0));
        
        ActionListener sharedLoginListener = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            sr_saveActionPerformed(evt);
        }
    };

        sr_name.addActionListener(sharedLoginListener);
        sr_username.addActionListener(sharedLoginListener);
        sr_password.addActionListener(sharedLoginListener);
        sr_conpass.addActionListener(sharedLoginListener);
        
        
    }
    public String capitalizeWords(String input) {
        String[] words = input.trim().toLowerCase().split("\\s+");
        StringBuilder sb = new StringBuilder();

        for (String word : words) {
            if (word.length() > 0) {
                sb.append(Character.toUpperCase(word.charAt(0)))
                  .append(word.substring(1))
                  .append(" ");
            }
        }
        

    return sb.toString().trim(); // remove the trailing space
}
        private boolean isValidInput(String input) {
            if (input.length() < 5) return false;

            boolean hasUpper = false;
            boolean hasDigit = false;
            boolean hasSpecial = false;

            for (char ch : input.toCharArray()) {
                if (Character.isUpperCase(ch)) hasUpper = true;
                else if (Character.isDigit(ch)) hasDigit = true;
                else if (!Character.isLetterOrDigit(ch)) hasSpecial = true;
            }

            return hasUpper && hasDigit && hasSpecial;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sr_username = new javax.swing.JTextField();
        sr_name = new javax.swing.JTextField();
        sr_conpass = new javax.swing.JPasswordField();
        sr_password = new javax.swing.JPasswordField();
        sr_clear = new javax.swing.JButton();
        sr_back = new javax.swing.JButton();
        sr_save = new javax.swing.JButton();
        sr_unhide = new javax.swing.JButton();
        sr_unhide1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        sr_username.setBackground(new java.awt.Color(255, 255, 255));
        sr_username.setForeground(new java.awt.Color(0, 0, 0));
        sr_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sr_username.setBorder(null);
        jPanel1.add(sr_username);
        sr_username.setBounds(400, 270, 170, 30);

        sr_name.setBackground(new java.awt.Color(255, 255, 255));
        sr_name.setForeground(new java.awt.Color(0, 0, 0));
        sr_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sr_name.setBorder(null);
        jPanel1.add(sr_name);
        sr_name.setBounds(370, 230, 200, 30);

        sr_conpass.setBackground(new java.awt.Color(255, 255, 255));
        sr_conpass.setForeground(new java.awt.Color(0, 0, 0));
        sr_conpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sr_conpass.setToolTipText("");
        sr_conpass.setBorder(null);
        jPanel1.add(sr_conpass);
        sr_conpass.setBounds(460, 350, 110, 30);

        sr_password.setBackground(new java.awt.Color(255, 255, 255));
        sr_password.setForeground(new java.awt.Color(0, 0, 0));
        sr_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sr_password.setToolTipText("");
        sr_password.setBorder(null);
        jPanel1.add(sr_password);
        sr_password.setBounds(390, 310, 180, 30);

        sr_clear.setBorderPainted(false);
        sr_clear.setContentAreaFilled(false);
        sr_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_clearActionPerformed(evt);
            }
        });
        jPanel1.add(sr_clear);
        sr_clear.setBounds(370, 420, 70, 30);

        sr_back.setBorderPainted(false);
        sr_back.setContentAreaFilled(false);
        sr_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_backActionPerformed(evt);
            }
        });
        jPanel1.add(sr_back);
        sr_back.setBounds(580, 500, 70, 30);

        sr_save.setBorderPainted(false);
        sr_save.setContentAreaFilled(false);
        sr_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_saveActionPerformed(evt);
            }
        });
        jPanel1.add(sr_save);
        sr_save.setBounds(460, 420, 70, 30);

        sr_unhide.setBorderPainted(false);
        sr_unhide.setContentAreaFilled(false);
        sr_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(sr_unhide);
        sr_unhide.setBounds(590, 310, 30, 20);

        sr_unhide1.setBorderPainted(false);
        sr_unhide1.setContentAreaFilled(false);
        sr_unhide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_unhide1ActionPerformed(evt);
            }
        });
        jPanel1.add(sr_unhide1);
        sr_unhide1.setBounds(590, 360, 30, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studreg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sr_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_saveActionPerformed
         String name = sr_name.getText();
        name = capitalizeWords(name);  
        sr_name.setText(name);
    
        String username = sr_username.getText();
        String password = sr_password.getText();
        String confirmpass = sr_conpass.getText();
        
        if (name.length() < 3) {
            JOptionPane.showMessageDialog(null, "Name must be at least 3 letters long.");
            sr_name.setText("");
            return;
        }

        if (username.length()<5) {
            JOptionPane.showMessageDialog(null, "Username must be at least 5 characters long");
            sr_username.setText("");
            return;
        }

        if (!isValidInput(password)) {
            JOptionPane.showMessageDialog(null, "Password must be at least 5 characters long and include an uppercase letter, a number, and a special character.");
            sr_password.setText("");
            return;
        }

        if (!isValidInput(confirmpass)) {
            JOptionPane.showMessageDialog(null,"Wrong Password");
            sr_conpass.setText("");            
            return;
            
        }

        if (!password.equals(confirmpass)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match. Please confirm the password again.");
            sr_conpass.setText("");
            return;
        }

        Finals_enrollment.username1.add(username);
        Finals_enrollment.password1.add(password);
        Finals_enrollment.name1.add(name);
        JOptionPane.showMessageDialog(null, "New Account Registered!");
       

        sr_password.setText("");
        sr_conpass.setText("");
        sr_name.setText("");
        sr_username.setText("");
        
              
    }//GEN-LAST:event_sr_saveActionPerformed

    private void sr_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_clearActionPerformed
        sr_password.setText("");
            sr_conpass.setText("");
            sr_name.setText("");
            sr_username.setText("");
    }//GEN-LAST:event_sr_clearActionPerformed

    private void sr_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_unhideActionPerformed
         if (sr_password.getEchoChar() == '*') {  
             sr_password.setEchoChar((char) 0);  
    } 
        else {
            sr_password.setEchoChar('*'); 
    }
    }//GEN-LAST:event_sr_unhideActionPerformed

    private void sr_unhide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_unhide1ActionPerformed
        if (sr_conpass.getEchoChar() == '*') {  
             sr_conpass.setEchoChar((char) 0);  
    } 
        else {
            sr_conpass.setEchoChar('*'); 
    }
    }//GEN-LAST:event_sr_unhide1ActionPerformed

    private void sr_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_backActionPerformed
        Finals_enrollment.previousFrame= ("StudentRegister");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sr_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F06_StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F06_StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F06_StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F06_StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F06_StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sr_back;
    private javax.swing.JButton sr_clear;
    private javax.swing.JPasswordField sr_conpass;
    private javax.swing.JTextField sr_name;
    private javax.swing.JPasswordField sr_password;
    private javax.swing.JButton sr_save;
    private javax.swing.JButton sr_unhide;
    private javax.swing.JButton sr_unhide1;
    private javax.swing.JTextField sr_username;
    // End of variables declaration//GEN-END:variables
}
