/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import javax.swing.JOptionPane;

/**
 *
 * @author aname
 */
public class F07_StaffRegister extends javax.swing.JFrame {

    /**
     * Creates new form F7_StaffRegister
     */
    public F07_StaffRegister() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ts_username = new javax.swing.JTextField();
        ts_name1 = new javax.swing.JTextField();
        tr_password = new javax.swing.JPasswordField();
        tr_conpass = new javax.swing.JPasswordField();
        tr_clear = new javax.swing.JButton();
        tr_back = new javax.swing.JButton();
        tr_save = new javax.swing.JButton();
        tr_unhide = new javax.swing.JButton();
        tr_unhide1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        ts_username.setBackground(new java.awt.Color(255, 255, 255));
        ts_username.setForeground(new java.awt.Color(0, 0, 0));
        ts_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ts_username.setBorder(null);
        jPanel1.add(ts_username);
        ts_username.setBounds(400, 260, 160, 30);

        ts_name1.setBackground(new java.awt.Color(255, 255, 255));
        ts_name1.setForeground(new java.awt.Color(0, 0, 0));
        ts_name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ts_name1.setBorder(null);
        jPanel1.add(ts_name1);
        ts_name1.setBounds(400, 210, 160, 30);

        tr_password.setBackground(new java.awt.Color(255, 255, 255));
        tr_password.setForeground(new java.awt.Color(0, 0, 0));
        tr_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tr_password.setToolTipText("");
        tr_password.setBorder(null);
        jPanel1.add(tr_password);
        tr_password.setBounds(400, 310, 160, 30);

        tr_conpass.setBackground(new java.awt.Color(255, 255, 255));
        tr_conpass.setForeground(new java.awt.Color(0, 0, 0));
        tr_conpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tr_conpass.setToolTipText("");
        tr_conpass.setBorder(null);
        jPanel1.add(tr_conpass);
        tr_conpass.setBounds(400, 360, 160, 30);

        tr_clear.setBorderPainted(false);
        tr_clear.setContentAreaFilled(false);
        tr_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_clearActionPerformed(evt);
            }
        });
        jPanel1.add(tr_clear);
        tr_clear.setBounds(420, 420, 60, 40);

        tr_back.setBorderPainted(false);
        tr_back.setContentAreaFilled(false);
        tr_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_backActionPerformed(evt);
            }
        });
        jPanel1.add(tr_back);
        tr_back.setBounds(530, 420, 60, 40);

        tr_save.setBorderPainted(false);
        tr_save.setContentAreaFilled(false);
        tr_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_saveActionPerformed(evt);
            }
        });
        jPanel1.add(tr_save);
        tr_save.setBounds(310, 423, 60, 40);

        tr_unhide.setBorderPainted(false);
        tr_unhide.setContentAreaFilled(false);
        tr_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(tr_unhide);
        tr_unhide.setBounds(570, 320, 30, 20);

        tr_unhide1.setBorderPainted(false);
        tr_unhide1.setContentAreaFilled(false);
        tr_unhide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_unhide1ActionPerformed(evt);
            }
        });
        jPanel1.add(tr_unhide1);
        tr_unhide1.setBounds(570, 370, 30, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerstaff.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tr_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_clearActionPerformed
            ts_name1.setText("");
            ts_username.setText("");
            tr_password.setText("");
            tr_conpass.setText("");
    }//GEN-LAST:event_tr_clearActionPerformed

    private void tr_unhide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_unhide1ActionPerformed
       if (tr_conpass.getEchoChar() == '*') {  
             tr_conpass.setEchoChar((char) 0);  
    } 
        else {
            tr_conpass.setEchoChar('*'); 
    }
    }//GEN-LAST:event_tr_unhide1ActionPerformed

    private void tr_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_unhideActionPerformed
        if (tr_password.getEchoChar() == '*') {  
             tr_password.setEchoChar((char) 0);  
    } 
        else {
            tr_password.setEchoChar('*'); 
    }
    }//GEN-LAST:event_tr_unhideActionPerformed

    private void tr_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_backActionPerformed
        Finals_enrollment.previousFrame= ("StaffRegister");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tr_backActionPerformed

    private void tr_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_saveActionPerformed
        String name = ts_name1.getText();
        String username = ts_username.getText();
        String password = tr_password.getText();
        String confirmpass = tr_conpass.getText();
     switch (Finals_enrollment.previousFrame) {
        case "ProfessorRegister":
            if (!name.isEmpty() && !username.isEmpty() && !password.isEmpty() && !confirmpass.isEmpty() && password.equals(confirmpass)) {
                Finals_enrollment.username.add(username);
                Finals_enrollment.password.add(password);
                JOptionPane.showMessageDialog(null, "New Account Registered!");
                ts_name1.setText("");
                ts_username.setText("");
                tr_password.setText("");
                tr_conpass.setText("");
            } else if (!password.equals(confirmpass)) {
                Finals_enrollment.username.add(username);
                Finals_enrollment.password.add(password);
                JOptionPane.showMessageDialog(null, "Please confirm the password again");
                tr_conpass.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "TRY AGAIN!");
                tr_password.setText("");
                tr_conpass.setText("");
            }
            break;

        case "RegistrarRegister":
            if (!name.isEmpty() && !username.isEmpty() && !password.isEmpty() && !confirmpass.isEmpty() && password.equals(confirmpass)) {
                Finals_enrollment.username2.add(username);
                Finals_enrollment.password2.add(password);
                JOptionPane.showMessageDialog(null, "New Account Registered!");
                ts_name1.setText("");
                ts_username.setText("");
                tr_password.setText("");
                tr_conpass.setText("");
            } else if (!password.equals(confirmpass)) {
                Finals_enrollment.username2.add(username);
                Finals_enrollment.password2.add(password);
                JOptionPane.showMessageDialog(null, "Please confirm the password again");
                tr_conpass.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "TRY AGAIN!");
                tr_password.setText("");
                tr_conpass.setText("");
            }
            break;
     }
    }//GEN-LAST:event_tr_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F07_StaffRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F07_StaffRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F07_StaffRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F07_StaffRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F07_StaffRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tr_back;
    private javax.swing.JButton tr_clear;
    private javax.swing.JPasswordField tr_conpass;
    private javax.swing.JPasswordField tr_password;
    private javax.swing.JButton tr_save;
    private javax.swing.JButton tr_unhide;
    private javax.swing.JButton tr_unhide1;
    private javax.swing.JTextField ts_name1;
    private javax.swing.JTextField ts_username;
    // End of variables declaration//GEN-END:variables
}
