package com.mycompany.finals_enrollment;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aname
 */
public class F08_Back extends javax.swing.JFrame {

    /**
     * Creates new form F8_Back
     */
    public F08_Back() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backno = new javax.swing.JButton();
        backyes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        backno.setBorderPainted(false);
        backno.setContentAreaFilled(false);
        backno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backnoActionPerformed(evt);
            }
        });
        jPanel1.add(backno);
        backno.setBounds(480, 330, 60, 30);

        backyes.setBorderPainted(false);
        backyes.setContentAreaFilled(false);
        backyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backyesActionPerformed(evt);
            }
        });
        jPanel1.add(backyes);
        backyes.setBounds(370, 330, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beck.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backyesActionPerformed
         if (Finals_enrollment.previousFrame.equals("AdminLogin")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        } else if (Finals_enrollment.previousFrame.equals("AdminPassword")) {
                new F03_AdminRegister().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("StudentRegister")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ProfessorRegister")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("Login")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("AdminBack")) {
                new F02_AdminLogin().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("BackManagement")) {
                new F14_AdminPortal().setVisible(true);
                this.setVisible(false);  
        }
    }//GEN-LAST:event_backyesActionPerformed

    private void backnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backnoActionPerformed
        if (Finals_enrollment.previousFrame.equals("AdminLogin")) {
                new F02_AdminLogin().setVisible(true);
                this.setVisible(false);
        } else if (Finals_enrollment.previousFrame.equals("AdminPassword")) {
                new F04_AdminPassword().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("StudentRegister")) {
                new F06_StudentRegister().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("Login")) {
                Finals_enrollment.previousFrame = "StudentLogin";
                new F09_LoginSS().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ProfessorLogin")) {
                Finals_enrollment.previousFrame = "ProfessorLogin"; 
                F09_LoginSS loginFrame = new F09_LoginSS();
                loginFrame.setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("AdminBack")) {
                new F03_AdminRegister().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("BackManagement")) {
                new F15_Management().setVisible(true);
                this.setVisible(false);
        }
    }//GEN-LAST:event_backnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F08_Back.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F08_Back.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F08_Back.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F08_Back.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F08_Back().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backno;
    private javax.swing.JButton backyes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
