/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author aname
 */
public class F09_LoginSS extends javax.swing.JFrame {

    /**
     * Creates new form F9_LoginSS
     */
    public F09_LoginSS() {
        initComponents();
        setLocationRelativeTo(null);
        login_password.setBackground(new Color(0, 0, 0, 0));
        login_username.setBackground(new Color(0, 0, 0, 0));
        
       ActionListener sharedLoginListener = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            login_enterActionPerformed(evt);
        }
    };

            login_username.addActionListener(sharedLoginListener);
            login_password.addActionListener(sharedLoginListener);
    }
    public void login(String username) {
       Finals_enrollment.cuser.clear(); // Clear previous entries
       Finals_enrollment.cuser.add(username); //
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_clear = new javax.swing.JButton();
        login_back = new javax.swing.JButton();
        login_enter = new javax.swing.JButton();
        login_username = new javax.swing.JTextField();
        login_unhide = new javax.swing.JButton();
        login_exit = new javax.swing.JButton();
        login_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        login_clear.setBorderPainted(false);
        login_clear.setContentAreaFilled(false);
        login_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_clearActionPerformed(evt);
            }
        });
        jPanel1.add(login_clear);
        login_clear.setBounds(370, 420, 60, 30);

        login_back.setBorderPainted(false);
        login_back.setContentAreaFilled(false);
        login_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_backActionPerformed(evt);
            }
        });
        jPanel1.add(login_back);
        login_back.setBounds(580, 500, 70, 30);

        login_enter.setBorderPainted(false);
        login_enter.setContentAreaFilled(false);
        login_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_enterActionPerformed(evt);
            }
        });
        jPanel1.add(login_enter);
        login_enter.setBounds(460, 420, 70, 30);

        login_username.setBackground(new java.awt.Color(255, 255, 255));
        login_username.setForeground(new java.awt.Color(0, 0, 0));
        login_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_username.setBorder(null);
        login_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(login_username);
        login_username.setBounds(410, 240, 160, 30);

        login_unhide.setBorderPainted(false);
        login_unhide.setContentAreaFilled(false);
        login_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(login_unhide);
        login_unhide.setBounds(580, 290, 30, 30);

        login_exit.setBorderPainted(false);
        login_exit.setContentAreaFilled(false);
        login_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_exitActionPerformed(evt);
            }
        });
        jPanel1.add(login_exit);
        login_exit.setBounds(250, 490, 60, 40);

        login_password.setBackground(new java.awt.Color(255, 255, 255));
        login_password.setForeground(new java.awt.Color(0, 0, 0));
        login_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_password.setBorder(null);
        jPanel1.add(login_password);
        login_password.setBounds(400, 290, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_exitActionPerformed

    private void login_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_enterActionPerformed
        String uname = login_username.getText();
        String pass = login_password.getText();

switch (Finals_enrollment.previousFrame) {
    case "StudentLogin" -> {
        int a = Finals_enrollment.username1.size();
        if (uname.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both username and password.");
        return;
    }

    if (Finals_enrollment.studentAttempts == 0) {
        JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
        login_enter.setEnabled(false);
        login_username.setEnabled(false);
        login_password.setEnabled(false);

        Finals_enrollment.studentTimer = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Finals_enrollment.studentAttempts = 3; 
                login_enter.setEnabled(true);
                login_username.setEnabled(true);
                login_password.setEnabled(true);
                login_username.setText("");
                login_password.setText("");
                JOptionPane.showMessageDialog(null, "You can try logging in again.");
                Finals_enrollment.studentTimer.stop();
            }
        });

                Finals_enrollment.studentTimer.setRepeats(false);
                Finals_enrollment.studentTimer.start();
                return;
            }

            boolean found = false;
 
            for (int i = 0; i < a; i++) {
                
                
                if (uname.equals(Finals_enrollment.username1.get(i))) {
                    found = true;
                    if (!pass.equals(Finals_enrollment.password1.get(i))) {
                        Finals_enrollment.studentAttempts--;
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname + ". Attempts left: " + Finals_enrollment.studentAttempts);
                        login_password.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F10_StudentPortal().setVisible(true);
                        this.setVisible(false);
                        Finals_enrollment.cuser.add(uname);
                    }
                    return;
                }
            }

            if (!found) {
                Finals_enrollment.studentAttempts--;
                JOptionPane.showMessageDialog(null, "Username doesn't exist! Attempts left: " + Finals_enrollment.studentAttempts);
                login_username.setText("");
                login_password.setText("");
            }

            if (Finals_enrollment.studentAttempts <= 0) {
                JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
                login_enter.setEnabled(false);
                login_username.setEnabled(false);
                login_password.setEnabled(false);

                Finals_enrollment.studentTimer = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Finals_enrollment.studentAttempts = 3;
                        login_enter.setEnabled(true);
                        login_username.setEnabled(true);
                        login_password.setEnabled(true);
                        login_username.setText("");
                        login_password.setText("");
                        JOptionPane.showMessageDialog(null, "You can try logging in again.");
                        Finals_enrollment.studentTimer.stop();
                    }
                });

                Finals_enrollment.studentTimer.setRepeats(false);
                Finals_enrollment.studentTimer.start();
            } 
    }

    case "ProfessorLogin" -> {
        int a = Finals_enrollment.username.size();
        
        if (uname.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both username and password.");
        return;
}

        if (Finals_enrollment.professorAttempts == 0) {
            JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
            login_enter.setEnabled(false);
            login_username.setEnabled(false);
            login_password.setEnabled(false);

        Finals_enrollment.professorTimer = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Finals_enrollment.professorAttempts = 3; 
                login_enter.setEnabled(true);
                login_username.setEnabled(true);
                login_password.setEnabled(true);
                login_username.setText("");
                login_password.setText("");
                JOptionPane.showMessageDialog(null, "You can try logging in again.");
                Finals_enrollment.professorTimer.stop();
            }
        });

                Finals_enrollment.professorTimer.setRepeats(false);
                Finals_enrollment.professorTimer.start();
                return;
            }

            boolean found = false;
            for (int i = 0; i < a; i++) {
                if (uname.equals(Finals_enrollment.username.get(i))) {
                    found = true;
                    if (!pass.equals(Finals_enrollment.password.get(i))) {
                        Finals_enrollment.professorAttempts--;
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname + ". Attempts left: " + Finals_enrollment.professorAttempts);
                        login_password.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F14_AdminPortal().setVisible(true);
                        this.setVisible(false);
                    }
                    return;
                }
            }

            if (!found) {
                Finals_enrollment.professorAttempts--;
                JOptionPane.showMessageDialog(null, "Username doesn't exist! Attempts left: " + Finals_enrollment.professorAttempts);
                login_username.setText("");
                login_password.setText("");
            }

            if (Finals_enrollment.professorAttempts <= 0) {
                JOptionPane.showMessageDialog(null, "Too many failed attempts. Access locked.");
                login_enter.setEnabled(false);
                login_username.setEnabled(false);
                login_password.setEnabled(false);

                Finals_enrollment.professorTimer = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Finals_enrollment.professorAttempts = 3;
                        login_enter.setEnabled(true);
                        login_username.setEnabled(true);
                        login_password.setEnabled(true);
                        login_username.setText("");
                        login_password.setText("");
                        JOptionPane.showMessageDialog(null, "You can try logging in again.");
                        Finals_enrollment.professorTimer.stop();
                    }
            });

            Finals_enrollment.professorTimer.setRepeats(false);
            Finals_enrollment.professorTimer.start();
        
        } else {
            JOptionPane.showMessageDialog(null, "Username doesn't exist!");
            login_username.setText("");
        }
    }
    
}

    }//GEN-LAST:event_login_enterActionPerformed

    private void login_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_clearActionPerformed
            login_username.setText("");
            login_password.setText("");
            
    }//GEN-LAST:event_login_clearActionPerformed

    private void login_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_backActionPerformed
        Finals_enrollment.previousFrame= ("Login");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_backActionPerformed

    private void login_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_unhideActionPerformed
        if (login_password.getEchoChar() == '*') {  
             login_password.setEchoChar((char) 0);  
    } 
        else {
            login_password.setEchoChar('*'); 
    }
    }//GEN-LAST:event_login_unhideActionPerformed

    private void login_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F09_LoginSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_back;
    private javax.swing.JButton login_clear;
    private javax.swing.JButton login_enter;
    private javax.swing.JButton login_exit;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JButton login_unhide;
    private javax.swing.JTextField login_username;
    // End of variables declaration//GEN-END:variables
}
