/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import javax.swing.JOptionPane;

/**
 *
 * @author aname
 */
public class F09_LoginSS extends javax.swing.JFrame {

    /**
     * Creates new form F9_LoginSS
     */
    public F09_LoginSS() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_clear = new javax.swing.JButton();
        login_back = new javax.swing.JButton();
        login_enter = new javax.swing.JButton();
        login_username = new javax.swing.JTextField();
        login_unhide = new javax.swing.JButton();
        login_exit = new javax.swing.JButton();
        login_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        login_clear.setBorderPainted(false);
        login_clear.setContentAreaFilled(false);
        login_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_clearActionPerformed(evt);
            }
        });
        jPanel1.add(login_clear);
        login_clear.setBounds(420, 390, 60, 30);

        login_back.setBorderPainted(false);
        login_back.setContentAreaFilled(false);
        login_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_backActionPerformed(evt);
            }
        });
        jPanel1.add(login_back);
        login_back.setBounds(500, 390, 70, 30);

        login_enter.setBorderPainted(false);
        login_enter.setContentAreaFilled(false);
        login_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_enterActionPerformed(evt);
            }
        });
        jPanel1.add(login_enter);
        login_enter.setBounds(330, 380, 70, 40);

        login_username.setBackground(new java.awt.Color(255, 255, 255));
        login_username.setForeground(new java.awt.Color(0, 0, 0));
        login_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_username.setBorder(null);
        jPanel1.add(login_username);
        login_username.setBounds(370, 250, 160, 30);

        login_unhide.setBorderPainted(false);
        login_unhide.setContentAreaFilled(false);
        login_unhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_unhideActionPerformed(evt);
            }
        });
        jPanel1.add(login_unhide);
        login_unhide.setBounds(540, 320, 30, 30);

        login_exit.setBorderPainted(false);
        login_exit.setContentAreaFilled(false);
        login_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_exitActionPerformed(evt);
            }
        });
        jPanel1.add(login_exit);
        login_exit.setBounds(780, 480, 60, 40);

        login_password.setBackground(new java.awt.Color(255, 255, 255));
        login_password.setForeground(new java.awt.Color(0, 0, 0));
        login_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_password.setBorder(null);
        jPanel1.add(login_password);
        login_password.setBounds(370, 320, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginboth.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_exitActionPerformed

    private void login_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_enterActionPerformed
        String uname = login_username.getText();
String pass = login_password.getText();

switch (Finals_enrollment.previousFrame) {
    case "StudentLogin" -> {
        int a = Finals_enrollment.username1.size();
        int i;

        if (Finals_enrollment.username1.contains(uname)) {
            for (i = 0; i < a;) {
                if (!uname.equals(Finals_enrollment.username1.get(i))) {
                    i++;
                } else {
                    if (!pass.equals(Finals_enrollment.password1.get(i))) {
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname);
                        login_password.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F10_StudentPortal().setVisible(true);
                        this.setVisible(false);
                        break;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username doesn't exist!");
            login_username.setText("");
        }
    }

    case "ProfessorLogin" -> {
        int a = Finals_enrollment.username.size();
        int i;

        if (Finals_enrollment.username.contains(uname)) {
            for (i = 0; i < a;) {
                if (!uname.equals(Finals_enrollment.username.get(i))) {
                    i++;
                } else {
                    if (!pass.equals(Finals_enrollment.password.get(i))) {
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname);
                        login_password.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F12_ProfessorPortal().setVisible(true);
                        this.setVisible(false);
                        break;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username doesn't exist!");
            login_username.setText("");
        }
    }
    case "RegistrarLogin" -> {
        int a = Finals_enrollment.username2.size();
        int i;

        if (Finals_enrollment.username2.contains(uname)) {
            for (i = 0; i < a;) {
                if (!uname.equals(Finals_enrollment.username2.get(i))) {
                    i++;
                } else {
                    if (!pass.equals(Finals_enrollment.password2.get(i))) {
                        JOptionPane.showMessageDialog(null, "Incorrect password for " + uname);
                        login_password.setText("");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
                        new F13_RegistrarPortal().setVisible(true);
                        this.setVisible(false);
                        break;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username doesn't exist!");
            login_username.setText("");
        }
    }

    default -> {
        JOptionPane.showMessageDialog(null, "Invalid login context!");
    }
}

    }//GEN-LAST:event_login_enterActionPerformed

    private void login_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_clearActionPerformed
            login_username.setText("");
            login_password.setText("");
            
    }//GEN-LAST:event_login_clearActionPerformed

    private void login_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_backActionPerformed
        Finals_enrollment.previousFrame= ("Login");
        new F08_Back().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_backActionPerformed

    private void login_unhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_unhideActionPerformed
        if (login_password.getEchoChar() == '*') {  
             login_password.setEchoChar((char) 0);  
    } 
        else {
            login_password.setEchoChar('*'); 
    }
    }//GEN-LAST:event_login_unhideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F09_LoginSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F09_LoginSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_back;
    private javax.swing.JButton login_clear;
    private javax.swing.JButton login_enter;
    private javax.swing.JButton login_exit;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JButton login_unhide;
    private javax.swing.JTextField login_username;
    // End of variables declaration//GEN-END:variables
}
