/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

/**
 *
 * @author aname
 */
public class F11_Exit extends javax.swing.JFrame {

    /**
     * Creates new form F11_Exit
     */
    public F11_Exit() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit_no = new javax.swing.JButton();
        exit_yes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        exit_no.setBorderPainted(false);
        exit_no.setContentAreaFilled(false);
        exit_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_noActionPerformed(evt);
            }
        });
        jPanel1.add(exit_no);
        exit_no.setBounds(480, 330, 60, 30);

        exit_yes.setBorderPainted(false);
        exit_yes.setContentAreaFilled(false);
        exit_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_yesActionPerformed(evt);
            }
        });
        jPanel1.add(exit_yes);
        exit_yes.setBounds(370, 330, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXIT.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_yesActionPerformed
         if (Finals_enrollment.previousFrame.equals("Homepage")) {
                System.exit(0);
         }else if (Finals_enrollment.previousFrame.equals("StudentPortalExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ProfessorExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("RegistrarPortalExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("AdminPortalExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ExitManagement")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("StudentPortalExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("EnrollmentExit")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }
    }//GEN-LAST:event_exit_yesActionPerformed

    private void exit_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_noActionPerformed
         if (Finals_enrollment.previousFrame.equals("Homepage")) {
                new F01_Homepage().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("StudentPortalExit")) {
                new F10_StudentPortal().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ProfessorExit")) {
                new F12_ProfessorPortal().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("AdminPortalExit")) {
                new F14_AdminPortal().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("ExitManagement")) {
                new F15_Management().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("StudentPortalExit")) {
                new F10_StudentPortal().setVisible(true);
                this.setVisible(false);
        }else if (Finals_enrollment.previousFrame.equals("EnrollmentExit")) {
                new F16_OnlineEnrollment().setVisible(true);
                this.setVisible(false);
        }
    }//GEN-LAST:event_exit_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F11_Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F11_Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F11_Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F11_Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F11_Exit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_no;
    private javax.swing.JButton exit_yes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
