/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author aname
 */
public class F15_SignUp extends javax.swing.JFrame {

   
    public F15_SignUp() {
        initComponents();
        setLocationRelativeTo(null);
        
        ActionListener sharedLoginListener = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            su_enterActionPerformed(evt);
        }
    };
        

        fname.addActionListener(sharedLoginListener);
        lname.addActionListener(sharedLoginListener);
        sex.addActionListener(sharedLoginListener);
        address.addActionListener(sharedLoginListener);
        course.addActionListener(sharedLoginListener);
        number.addActionListener(sharedLoginListener);
        
        
        fname.setBackground(new Color(0, 0, 0, 0));
        lname.setBackground(new Color(0, 0, 0, 0));
        sex.setBackground(new Color(0, 0, 0, 0));
        address.setBackground(new Color(0, 0, 0, 0));
        number.setBackground(new Color(0, 0, 0, 0));
        course.setBackground(new Color(0, 0, 0, 0));
        
        number.setText("09");

        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                String text = number.getText();
                int caret = number.getCaretPosition();
                char c = evt.getKeyChar();

                if (!Character.isDigit(c)) {
                    evt.consume();
                    return;
                }

                if (caret < 2) {
                    evt.consume();
                    return;
                }

                if (text.length() >= 11) {
                    evt.consume();
                }
            }

            public void keyPressed(java.awt.event.KeyEvent evt) {
                int pos = number.getCaretPosition();
                if ((evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE ||
                     evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) && pos <= 2) {
                    evt.consume();
                }
            }
        });

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        fname = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        su_back = new javax.swing.JButton();
        su_enter = new javax.swing.JButton();
        su_clear = new javax.swing.JButton();
        course = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setToolTipText("");
        lname.setBorder(null);
        jPanel1.add(lname);
        lname.setBounds(410, 280, 180, 20);

        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        jPanel1.add(address);
        address.setBounds(380, 330, 200, 20);

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sex", "female", "male" }));
        sex.setBorder(null);
        jPanel1.add(sex);
        sex.setBounds(350, 310, 72, 20);

        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(null);
        jPanel1.add(fname);
        fname.setBounds(410, 250, 170, 20);

        number.setForeground(new java.awt.Color(0, 0, 0));
        number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number.setBorder(null);
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel1.add(number);
        number.setBounds(440, 360, 150, 16);

        su_back.setBorderPainted(false);
        su_back.setContentAreaFilled(false);
        jPanel1.add(su_back);
        su_back.setBounds(580, 500, 70, 30);

        su_enter.setBorderPainted(false);
        su_enter.setContentAreaFilled(false);
        su_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_enterActionPerformed(evt);
            }
        });
        jPanel1.add(su_enter);
        su_enter.setBounds(460, 420, 70, 30);

        su_clear.setBorderPainted(false);
        su_clear.setContentAreaFilled(false);
        jPanel1.add(su_clear);
        su_clear.setBounds(370, 420, 70, 30);

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "course", "BS Information Technology", "BA Marketing", "BS Nursing", "BS Psychology" }));
        course.setBorder(null);
        jPanel1.add(course);
        course.setBounds(430, 380, 160, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void su_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_enterActionPerformed
            String sfname = fname.getText().trim();
            String slname = lname.getText().trim();
            String ssex = sex.getSelectedItem().toString();
            String saddress = address.getText().trim();
            String snumber = number.getText().trim(); // Now as String
            String scourse = course.getSelectedItem().toString();
            

            if (sfname.length() < 2) {
                JOptionPane.showMessageDialog(null, "First name must be at least 2 characters long.");
                return;
            }

            if (slname.length() < 2) {
                JOptionPane.showMessageDialog(null, "Last name must be at least 2 characters long.");
                return;
            }

            if (!(ssex.equalsIgnoreCase("male") || ssex.equalsIgnoreCase("female"))) {
                JOptionPane.showMessageDialog(null, "Please select your sex.");
                return;
            }

            if (saddress.length() < 15) {
                JOptionPane.showMessageDialog(null, "Address must be at least 15 characters long.");
                return;
            }

            if (!snumber.matches("\\d{11}")) {
                JOptionPane.showMessageDialog(null, "Phone number must be exactly 11 digits (e.g., 09123456789).");
                return;
                
            }

            if (scourse.equalsIgnoreCase("course")) {
                JOptionPane.showMessageDialog(null, "Please select your course.");
                return;
    }

    
    JOptionPane.showMessageDialog(null, "Sign-up successful!");
    }//GEN-LAST:event_su_enterActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F15_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F15_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F15_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F15_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F15_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField number;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JButton su_back;
    private javax.swing.JButton su_clear;
    private javax.swing.JButton su_enter;
    // End of variables declaration//GEN-END:variables
}
