/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;
import java.awt.Color;
/**
 *
 * @author aname
 */
public class F15_StudentEditInformation extends javax.swing.JFrame {

    /**
     * Creates new form F15_StudentEditInformation
     */
    public F15_StudentEditInformation() {
        initComponents();
        setLocationRelativeTo(null);
        stud_sex.setBackground(new java.awt.Color(0, 0, 0, 0));
        stud_surname.setBackground(new java.awt.Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stud_sex = new javax.swing.JComboBox<>();
        stud_surname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        stud_sex.setBackground(new java.awt.Color(255, 255, 255));
        stud_sex.setForeground(new java.awt.Color(0, 0, 0));
        stud_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        stud_sex.setBorder(null);
        stud_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_sexActionPerformed(evt);
            }
        });
        jPanel1.add(stud_sex);
        stud_sex.setBounds(100, 230, 100, 30);

        stud_surname.setForeground(new java.awt.Color(0, 0, 0));
        stud_surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stud_surname.setToolTipText("");
        stud_surname.setBorder(null);
        stud_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_surnameActionPerformed(evt);
            }
        });
        jPanel1.add(stud_surname);
        stud_surname.setBounds(220, 230, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit information.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stud_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stud_sexActionPerformed

    private void stud_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stud_surnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F15_StudentEditInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F15_StudentEditInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F15_StudentEditInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F15_StudentEditInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F15_StudentEditInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> stud_sex;
    private javax.swing.JTextField stud_surname;
    // End of variables declaration//GEN-END:variables
}
