/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finals_enrollment;

import java.awt.Color;

/**
 *
 * @author aname
 */
public class F16_OnlineEnrollment extends javax.swing.JFrame {

    /**
     * Creates new form F16_OnlineEnrollment
     */
    public F16_OnlineEnrollment() {
        initComponents();
        setLocationRelativeTo(null);
        studentname.setBackground(new Color(0, 0, 0, 0));
        year.setBackground(new Color(0, 0, 0, 0));
        term.setBackground(new Color(0, 0, 0, 0));
        section.setBackground(new Color(0, 0, 0, 0));
        course.setBackground(new Color(0, 0, 0, 0));
        
        String name = Finals_enrollment.name1.get(Finals_enrollment.name1.size() - 1);

        studentname.setText(name);
        
        year.addActionListener(e -> updateSections());
        course.addActionListener(e -> updateSections());
        term.addActionListener(e -> updateSections());

        
        
    }
    
    private void updateSections() {
    section.removeAllItems();

    String Year = (String) year.getSelectedItem();
    String Course = (String) course.getSelectedItem();
    String Term = (String) term.getSelectedItem();

    if (Year == null || Course == null || Term == null) return;

    if ("BS Information Technology".equals(Course)) {
        if ("1st".equals(Year)) {
            section.addItem("401IT");
            section.addItem("402IT");
        } else if ("2nd".equals(Year)) {
            section.addItem("301IT");
            section.addItem("302IT");
        } else if ("3rd".equals(Year)) {
            section.addItem("201IT");
            section.addItem("202IT");
        } else if ("4th".equals(Year)) {
            section.addItem("101IT");
            section.addItem("102IT");
        }
    } else if ("BS Psychology".equals(Course)) {
        if ("1st".equals(Year)) {
            section.addItem("401PS");
            section.addItem("402PS");
        } else if ("2nd".equals(Year)) {
            section.addItem("301PS");
            section.addItem("302PS");
        } else if ("3rd".equals(Year)) {
            section.addItem("201PS");
            section.addItem("202PS");
        } else if ("4th".equals(Year)) {
            section.addItem("101PS");
            section.addItem("102PS");
        }
    } else if ("BS Nursing".equals(Course)) {
        if ("1st".equals(Year)) {
            section.addItem("401NS");
            section.addItem("402NS");
        } else if ("2nd".equals(Year)) {
            section.addItem("301NS");
            section.addItem("302NS");
        } else if ("3rd".equals(Year)) {
            section.addItem("201NS");
            section.addItem("202NS");
        } else if ("4th".equals(Year)) {
            section.addItem("101NS");
            section.addItem("102NS");
        }
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        term = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        section = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        studentname = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        term.setForeground(new java.awt.Color(0, 0, 0));
        term.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd" }));
        term.setBorder(null);
        jPanel1.add(term);
        term.setBounds(150, 300, 340, 40);

        course.setForeground(new java.awt.Color(0, 0, 0));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS Information Technology", "BS Psychology", "BS Nursing" }));
        course.setBorder(null);
        jPanel1.add(course);
        course.setBounds(160, 390, 330, 40);

        section.setForeground(new java.awt.Color(0, 0, 0));
        section.setBorder(null);
        jPanel1.add(section);
        section.setBounds(160, 340, 330, 40);

        year.setForeground(new java.awt.Color(0, 0, 0));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));
        year.setBorder(null);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year);
        year.setBounds(150, 250, 340, 40);

        studentname.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        studentname.setBorder(null);
        jPanel1.add(studentname);
        studentname.setBounds(210, 212, 290, 30);

        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(790, 500, 80, 30);

        back.setBackground(new java.awt.Color(255, 255, 102));
        back.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("Back");
        back.setBorder(null);
        jPanel1.add(back);
        back.setBounds(30, 500, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ENROLL.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Finals_enrollment.previousFrame= ("EnrollmentExit");
        new F11_Exit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F16_OnlineEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F16_OnlineEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F16_OnlineEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F16_OnlineEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F16_OnlineEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JTextField studentname;
    private javax.swing.JComboBox<String> term;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
